### ISSUE TITLE
unable to start ... has no method 'concat'

### ISSUE THREAD

**Issue by pacmac** [OneOfOne/dynamic-routes#1]
Hi;

I have just installed and tested your dynamic routing, however it fails when I attempt to run the app. I have used the example app.js and index.js files which you provided as usage examples.

```
 #:/usr/share/nodejs# node /usr/share/nodejs/dqm/app.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
load /usr/share/nodejs/dqm/routes/index.js

/usr/share/nodejs/dqm/node_modules/express/lib/utils.js:298
    .concat(strict ? '' : '/?')
     ^
TypeError: Object function (req, res) {} has no method 'concat'
    at Object.exports.pathRegexp (/usr/share/nodejs/dqm/node_modules/express/lib/utils.js:298:6)
    at new Route (/usr/share/nodejs/dqm/node_modules/express/lib/router/route.js:35:23)
    at Router.route (/usr/share/nodejs/dqm/node_modules/express/lib/router/index.js:296:15)
    at Router.(anonymous function) [as head] (/usr/share/nodejs/dqm/node_modules/express/lib/router/index.js:318:16)
    at Function.app.(anonymous function) [as head] (/usr/share/nodejs/dqm/node_modules/express/lib/application.js:412:26)
    at Object.module.exports.init (/usr/share/nodejs/dqm/routes/index.js:8:13)
    at Object.module.exports.DynamicRoutes.install (/usr/share/nodejs/node_modules/dynamic-routes/lib/dynamic-routes.js:94:48)
    at E.priority (/usr/share/nodejs/node_modules/dynamic-routes/lib/dynamic-routes.js:104:6)
    at Object.<anonymous> (/usr/share/nodejs/dqm/app.js:21:1)
    at Module._compile (module.js:456:26)
```

**Comment by OneOfOne** [comment]
I've sense moved to Go from NodeJS however I pushed a fix.

Basically you can't use app.head() anymore in express.

**Comment by OneOfOne** [comment]
I'm not sure why, is it version 0.0.3?
Can you should me the code you used to reproduce it?

**Comment by diginfo** [comment]
My apologies, I thought you had changed the module, I did not realize that the change you made was to the example code.

I need to enable middleware to verify the users login session and credentials.

How can i force every request to be routed via a fixed route which contains my verification code, or how can I integrate middleware with dynamic-routes ?

**Comment by OneOfOne** [comment]
Either enable it for all using `express.use(.....)` before you plug this
module or simply add an extra function to your route and inside it
`if(authorized()<<your code) { callRealHandler(); }`.
